<a href="https://colab.research.google.com/github/paulgureghian/Google_Colab_Notebooks/blob/master/Flatten_a_PyTorch_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Created by Paul A. Gureghian on 11/22/18.** 

**This notbook shows how to flatten a Pytorch tensor,**

**by using the PyTorch view operation.**

In [1]:
### install pytorch

!pip3 install -U -q http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl

tcmalloc: large alloc 1073750016 bytes == 0x57712000 @  0x7f3d34c742a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641


In [0]:
### import torch 

import torch

In [3]:
### print torch version 

print(torch.__version__)

0.4.1


In [0]:
### create an initial pytorch tensor

pt_initial_tensor_ex = torch.Tensor(
[
    [
         [ 1, 2, 3, 4],
         [ 5, 6, 7, 8]
    ]
    ,
    [
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]
    ]
    ,
    [
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])       

In [12]:
### shape of tensor 

print("shape of tensor: ", pt_initial_tensor_ex.shape) 

shape of tensor:  torch.Size([3, 2, 4])


In [17]:
### print the tensor 

print("pt_init_tensor_ex:\n ", pt_initial_tensor_ex) 

pt_init_tensor_ex:
  tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]],

        [[17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [0]:
### flatten the tensor to a list of 24 elements 

pt_flattened_tensor_ex =  pt_initial_tensor_ex.view(-1) 

In [21]:
### shape of flattened tensor 

print("shape of flattened tensor: ", pt_flattened_tensor_ex.shape) 

shape of flattened tensor:  torch.Size([24])


In [22]:
### print the flattened tensor 

print("pt_flattened_tensor_ex:\n ", pt_flattened_tensor_ex)

pt_flattened_tensor_ex:
  tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])


In [23]:
### check that the original tensor did not change in place 

print("shape of init tensor: ", pt_initial_tensor_ex.shape) 
print('')
print("pt_init_tensor_ex:\n ", pt_initial_tensor_ex) 

shape of init tensor:  torch.Size([3, 2, 4])

pt_init_tensor_ex:
  tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]],

        [[17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


**We flattened a PyTorch tensor with the PyTorch view operation and the negative one.**