<a href="https://colab.research.google.com/github/paulgureghian/Google_Colab_Notebooks/blob/master/Numpy_to_Pytorch_and_back_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**How to convert Numpy arrays to Pytorch tensors.**

**And how to convert Pytorch tensors to Numpy arrays.**

In [0]:
### install pytorch 
!pip3 install -U -q http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl

tcmalloc: large alloc 1073750016 bytes == 0x588e4000 @  0x7f78b9db72a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641


In [0]:
### import packages
import torch
import numpy as np

In [0]:
### create a 4 X 3 numpy array
a = np.random.rand(4,3)
a

array([[0.48118521, 0.44220094, 0.6206832 ],
       [0.80926846, 0.54362624, 0.90551087],
       [0.1272961 , 0.59223918, 0.54121959],
       [0.20503115, 0.70358754, 0.12773411]])

In [0]:
### convert numpy array to pytorch tensor
b = torch.from_numpy(a)
b

tensor([[0.4812, 0.4422, 0.6207],
        [0.8093, 0.5436, 0.9055],
        [0.1273, 0.5922, 0.5412],
        [0.2050, 0.7036, 0.1277]], dtype=torch.float64)

In [0]:
### convert pytorch tensor to numpy array
b.numpy()


array([[0.48118521, 0.44220094, 0.6206832 ],
       [0.80926846, 0.54362624, 0.90551087],
       [0.1272961 , 0.59223918, 0.54121959],
       [0.20503115, 0.70358754, 0.12773411]])

In [0]:
### multiply pytorch tensor by 2, in place
b.mul_(2)

tensor([[0.9624, 0.8844, 1.2414],
        [1.6185, 1.0873, 1.8110],
        [0.2546, 1.1845, 1.0824],
        [0.4101, 1.4072, 0.2555]], dtype=torch.float64)

In [0]:
### numpy array matches new values from pytorch tensor
a

array([[0.96237043, 0.88440189, 1.24136639],
       [1.61853692, 1.08725248, 1.81102174],
       [0.2545922 , 1.18447836, 1.08243919],
       [0.41006229, 1.40717508, 0.25546822]])