<a href="https://colab.research.google.com/github/paulgureghian/Google_Colab_Notebooks/blob/master/Scale_a_PyTorch_tensor_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Created by Paul A. Gureghian on 11/29/18.**

**This notebook tutorial shows how to fill a PyTorch tensor**

**with a certain scalar using the PyTorch fill operation.**

In [0]:
### Install PyTorch and CUDA
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

In [0]:
### Import Torch
import torch

In [12]:
### Print the Torch version 
print(torch.__version__)

0.4.1


In [0]:
### Initialize a PyTorch tensor 
pt_tensor_empty_ex = torch.Tensor(2, 4, 6)

In [14]:
### Print the Tensor 
print(pt_tensor_empty_ex)

tensor([[[ 2.2136e-37,  0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,
           0.0000e+00],
         [ 7.2051e-37,  0.0000e+00, -9.0871e-09,  4.5736e-41,  7.2532e-37,
           0.0000e+00],
         [-1.6912e-37,  4.5736e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  7.8435e-37,
           0.0000e+00]],

        [[ 7.8435e-37,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  7.5514e+28,  0.0000e+00,  0.0000e+00,
           0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00]]])


In [0]:
### Fill the Tensor with the scalar 12345
pt_tensor_filled_ex = pt_tensor_empty_ex.fill_(12345) 

In [16]:
### Print the filled Tensor
print(pt_tensor_filled_ex)

tensor([[[12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.]],

        [[12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.]]])


In [17]:
### Since we did an in-place operation with 'fill_'
### The empty Tensor also gets filled with the scalar
print(pt_tensor_empty_ex)

tensor([[[12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.]],

        [[12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.],
         [12345., 12345., 12345., 12345., 12345., 12345.]]])
