[View in Colaboratory](https://colab.research.google.com/github/paulgureghian/Google_Colab_Notebooks/blob/master/Train_Test_Split_.ipynb)

**Click "File" > "Save a copy in Drive", then press "Runtime" > "Run all", in the copy.**

**Created by Paul A. Gureghian on 9/4/2018.**

**Data splitting with Scikit-Learn **
** Using the train_test_split function for data analysis as part of a Machine Learning project.** 

**You should split your dataset before you begin modeling.**
**First fit the model on the training set, then estimate your model performance with the testing set. ** 

In [0]:
# import packages 

import numpy as np 
from sklearn.model_selection import KFold
import sklearn.model_selection as model_selection 
import sklearn.cross_validation as cross_validation 

In [44]:
# define X for features 

X = list(range(10)) 
print(X) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [45]:
# define y for labels 

y = [x * x for x in X] 
print(y) 

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [46]:
# split data into two sets 

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size =0.75, test_size =0.25, random_state =101)

print("X_train: ", X_train)
print("y_train: ", y_train)
print("X_test: ", X_test)
print("y_test: ", y_test) 

X_train:  [4, 9, 3, 5, 7, 6, 1]
y_train:  [16, 81, 9, 25, 49, 36, 1]
X_test:  [8, 2, 0]
y_test:  [64, 4, 0]


In [47]:
# split data the old way 

X_train, X_test, y_test, y_train = cross_validation.train_test_split(X, y, train_size =0.75, test_size =0.25, random_state =101)

print("X_train: ", X_train)
print("y_train: ", y_train)
print("X_test: ", X_test)
print("y_train: ", y_train) 

X_train:  [4, 9, 3, 5, 7, 6, 1]
y_train:  [64, 4, 0]
X_test:  [8, 2, 0]
y_train:  [64, 4, 0]


In [48]:
# split data into n consecutive folds with the KFold() function

kf = KFold(n_splits=5, shuffle =True) 
X_array = np.array(X)
y_array = np.array(y) 

print("X_array:", X_array)
print("y_array:", y_array) 
print('')

for train_index, test_index in kf.split(X):
    X_train, X_test = X_array[train_index], X_array[test_index]
    y_train, y_test = y_array[train_index], y_array[test_index]
    
    print("X_train:", X_train)
    print('')
    print("X_test:", X_test)
    print('')
    print("y_train:", y_train)
    print('')
    print("y_test", y_test) 
    print('') 

X_array: [0 1 2 3 4 5 6 7 8 9]
y_array: [ 0  1  4  9 16 25 36 49 64 81]

X_train: [0 1 2 4 5 6 7 8]

X_test: [3 9]

y_train: [ 0  1  4 16 25 36 49 64]

y_test [ 9 81]

X_train: [1 3 4 5 6 7 8 9]

X_test: [0 2]

y_train: [ 1  9 16 25 36 49 64 81]

y_test [0 4]

X_train: [0 2 3 4 6 7 8 9]

X_test: [1 5]

y_train: [ 0  4  9 16 36 49 64 81]

y_test [ 1 25]

X_train: [0 1 2 3 4 5 6 9]

X_test: [7 8]

y_train: [ 0  1  4  9 16 25 36 81]

y_test [49 64]

X_train: [0 1 2 3 5 7 8 9]

X_test: [4 6]

y_train: [ 0  1  4  9 25 49 64 81]

y_test [16 36]



In [49]:
X_train

array([0, 1, 2, 3, 5, 7, 8, 9])

In [50]:
X_test

array([4, 6])

In [51]:
y_train 

array([ 0,  1,  4,  9, 25, 49, 64, 81])

In [52]:
y_test 

array([16, 36])